const state=JSON.parse(localStorage.getItem('workbook-progress')||'{}');
const settings=JSON.parse(localStorage.getItem('workbook-settings')||'{"mode":"guided","theme":"dark"}');
if(!settings.theme)settings.theme='dark';
const app=document.querySelector('#app');let current=null;
function key(t,s){return `T${t}-S${s}`}
function save(){localStorage.setItem('workbook-progress',JSON.stringify(state));updateProgress()}
function saveSettings(){localStorage.setItem('workbook-settings',JSON.stringify(settings))}
function applyTheme(){document.documentElement.dataset.theme=settings.theme;const b=document.querySelector('#themeToggle');if(b){b.innerHTML=settings.theme==='dark'?'☀ <span>Thème clair</span>':'☾ <span>Thème sombre</span>';b.setAttribute('aria-label',settings.theme==='dark'?'Activer le thème clair':'Activer le thème sombre')}const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content=settings.theme==='dark'?'#07111f':'#f6f3ed'}
function updateProgress(){const done=Object.values(state).filter(v=>v==='done').length;document.querySelector('#progressText').textContent=`${done} sujet${done>1?'s':''} terminé${done>1?'s':''} sur 81`;document.querySelector('#progressBar').style.width=`${done/81*100}%`;const orbit=document.querySelector('.hero-orbit span');if(orbit)orbit.textContent=`${Math.round(done/81*100)}%`}
function modePicker(){return `<div class="mode-picker"><button class="mode ${settings.mode==='guided'?'active':''}" data-mode="guided"><span class="mode-number">1</span><div><b>Niveau 1</b><span>Guidé avec pastilles</span></div></button><button class="mode ${settings.mode==='free'?'active':''}" data-mode="free"><span class="mode-number">2</span><div><b>Niveau 2</b><span>Réponse écrite ou orale</span></div></button></div>`}
function bindModeButtons(onChange){document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{settings.mode=b.dataset.mode;saveSettings();onChange()})}
function renderHome(){current=null;app.innerHTML=`<div class="section-heading"><div><p class="eyebrow">PARCOURS D’APPRENTISSAGE</p><h2>Les 19 thèmes du cahier</h2></div><span class="section-badge">Circuit DGFiP</span></div>`+modePicker()+window.WORKBOOK_PARTS.map(p=>`<details open class="part"><summary><span>${p.n}</span><div><b>Partie ${p.n}</b><small>${p.t}</small></div><i>${p.themes.length} thèmes</i></summary>${p.themes.map(t=>`<details class="theme"><summary><div class="theme-node"><span>${t.n}</span></div><div><b>Thème ${t.n} — ${t.t}</b><small>${t.s.length} sujet${t.s.length>1?'s':''}</small></div></summary><div class="subjects">${t.s.map((title,i)=>{const k=key(t.n,i+1);const status=state[k]||'todo';return `<button class="subject ${status}" data-theme="${t.n}" data-subject="${i+1}"><span>${status==='done'?'✓':i+1}</span><div><b>${title}</b><small>${status==='done'?'Maîtrisé':window.EXERCISES[k]?'Disponible':'En cours d’intégration'}</small></div><i>›</i></button>`}).join('')}</div></details>`).join('')}</details>`).join('');document.querySelectorAll('.subject').forEach(b=>b.onclick=()=>openSubject(+b.dataset.theme,+b.dataset.subject));bindModeButtons(renderHome)}
function findTheme(n){for(const p of window.WORKBOOK_PARTS){const t=p.themes.find(x=>x.n===n);if(t)return{part:p,theme:t}}}
function variantFor(ex,k){const seed=+(localStorage.getItem(`${k}-variant`)||0);if(!ex||!ex.variants||!ex.variants.length)return ex;return {...ex,...ex.variants[seed%ex.variants.length]}}
function chips(q,i,k){const choices=q.choices||[];return `<div class="chips" data-question="${i}">${choices.map(c=>`<button type="button" class="chip" data-value="${String(c).replace(/"/g,'&quot;')}">${c}</button>`).join('')}</div><input type="hidden" data-answer="${i}" value="${localStorage.getItem(`${k}-a${i}`)||''}">`}
function tableBlock(table){if(!table)return'';return `<div class="table-wrap"><table><thead><tr>${table.headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${table.rows.map(row=>`<tr>${row.map(cell=>`<td>${cell}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function questionBlock(q,i,k){const answer=localStorage.getItem(`${k}-a${i}`)||'';if(settings.mode==='guided'&&q.choices?.length)return `<div class="question"><div class="question-label"><span>${i+1}</span><b>Question ${i+1}</b></div><p>${q.text||q}</p>${chips(q,i,k)}</div>`;return `<div class="question"><div class="question-label"><span>${i+1}</span><b>Question ${i+1}</b></div><span>${q.text||q}</span><textarea data-answer="${i}" placeholder="Rédige ta réponse…">${answer}</textarea>${settings.mode==='free'?`<div class="voice-controls"><button type="button" class="voice-btn" data-voice="${i}" aria-label="Répondre à l’oral">🎙 Répondre à l’oral</button><small class="voice-status" data-voice-status="${i}" aria-live="polite"></small></div>`:''}</div>`}
function bindSpeech(k){const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;document.querySelectorAll('.voice-btn').forEach(button=>{const i=button.dataset.voice;const textarea=document.querySelector(`textarea[data-answer="${i}"]`);const status=document.querySelector(`[data-voice-status="${i}"]`);if(!SpeechRecognition){button.disabled=true;button.textContent='🎙 Dictée non disponible';status.textContent='Utilise Chrome sur Android pour la réponse orale.';return}let recognition=null;let listening=false;button.onclick=()=>{if(listening&&recognition){recognition.stop();return}recognition=new SpeechRecognition();recognition.lang='fr-FR';recognition.continuous=false;recognition.interimResults=true;const initial=textarea.value.trim();let spoken='';recognition.onstart=()=>{listening=true;button.classList.add('listening');button.textContent='■ Arrêter';status.textContent='Je t’écoute…'};recognition.onresult=e=>{spoken=Array.from(e.results).map(r=>r[0].transcript).join(' ').trim();textarea.value=[initial,spoken].filter(Boolean).join(initial&&spoken?' ':'');localStorage.setItem(`${k}-a${i}`,textarea.value)};recognition.onerror=e=>{const messages={not_allowed:'Autorise le microphone dans les réglages du navigateur.',no_speech:'Aucune parole détectée. Appuie de nouveau pour recommencer.',network:'La reconnaissance vocale nécessite une connexion internet sur cet appareil.'};status.textContent=messages[e.error]||'La dictée a été interrompue.'};recognition.onend=()=>{listening=false;button.classList.remove('listening');button.textContent='🎙 Répondre à l’oral';if(spoken)status.textContent='Réponse ajoutée. Tu peux la corriger dans la zone de texte.'};try{recognition.start()}catch{status.textContent='Le microphone est déjà en cours d’utilisation.'}}})}
function openSubject(tn,sn){current={tn,sn};const {part,theme}=findTheme(tn);const title=theme.s[sn-1];const k=key(tn,sn);const base=window.EXERCISES[k];const ex=variantFor(base,k);app.innerHTML=`<button class="back">← Sommaire</button>${modePicker()}<article class="exercise"><div class="exercise-head"><div><p class="eyebrow">PARTIE ${part.n} · THÈME ${tn} · SUJET ${sn}/${theme.s.length}</p><h2>${title}</h2></div>${ex?`<button id="newVariant" class="refresh" title="Changer uniquement les noms, dates, quantités et montants" aria-label="Nouvelle variante">↻</button>`:''}</div><div class="level-badge">${settings.mode==='guided'?'Niveau 1 · avec pastilles':'Niveau 2 · réponse écrite ou orale'}</div>${ex?`<section class="exercise-panel"><h3>Énoncé</h3><div class="statement">${ex.statement}</div>${tableBlock(ex.table)}</section><section class="exercise-panel"><h3>Travail à faire</h3>${(ex.questions||[]).map((q,i)=>questionBlock(q,i,k)).join('')}</section><button id="showCorrection">Afficher le corrigé</button><section id="correction" class="exercise-panel correction-panel" hidden><h3>Corrigé</h3><div class="statement">${ex.correction}</div>${tableBlock(ex.correctionTable)}</section>`:`<div class="pending"><b>Ce sujet n’est pas encore retranscrit.</b><p>Aucun exercice inventé ne sera affiché. Le contenu exact sera ajouté à partir du PDF source.</p></div>`}<div class="actions"><button id="markDone" class="primary">${state[k]==='done'?'Marquer à refaire':'Marquer comme terminé'}</button></div></article>`;document.querySelector('.back').onclick=renderHome;bindModeButtons(()=>openSubject(tn,sn));document.querySelectorAll('textarea').forEach(a=>a.oninput=()=>localStorage.setItem(`${k}-a${a.dataset.answer}`,a.value));if(settings.mode==='free')bindSpeech(k);document.querySelectorAll('.chips').forEach(group=>group.querySelectorAll('.chip').forEach(chip=>chip.onclick=()=>{group.querySelectorAll('.chip').forEach(c=>c.classList.remove('selected'));chip.classList.add('selected');localStorage.setItem(`${k}-a${group.dataset.question}`,chip.dataset.value)}));const show=document.querySelector('#showCorrection');if(show)show.onclick=()=>{const c=document.querySelector('#correction');c.hidden=!c.hidden;show.textContent=c.hidden?'Afficher le corrigé':'Masquer le corrigé'};const refresh=document.querySelector('#newVariant');if(refresh)refresh.onclick=()=>{const next=+(localStorage.getItem(`${k}-variant`)||0)+1;localStorage.setItem(`${k}-variant`,String(next));openSubject(tn,sn)};document.querySelector('#markDone').onclick=()=>{state[k]=state[k]==='done'?'todo':'done';save();openSubject(tn,sn)}}
document.querySelector('#resetBtn').onclick=()=>{if(confirm('Réinitialiser toute la progression ?')){localStorage.removeItem('workbook-progress');Object.keys(state).forEach(k=>delete state[k]);renderHome();updateProgress()}};
document.querySelector('#themeToggle').onclick=()=>{settings.theme=settings.theme==='dark'?'light':'dark';saveSettings();applyTheme()};
let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;const b=document.querySelector('#installBtn');b.hidden=false;b.onclick=async()=>{deferred.prompt();await deferred.userChoice;b.hidden=true}});if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');applyTheme();renderHome();updateProgress();