window.EXERCISES=window.EXERCISES||{};
Object.assign(window.EXERCISES,{
'T3-S1':{
 statement:`Monsieur Lecarvozin crée une entreprise individuelle le 3 avril N. Son activité ne nécessite pas de stockage. Le bilan de départ comprend : fonds commercial 20 000 €, matériel de transport 17 000 €, matériel de bureau 5 000 €, mobilier 2 000 €, banque 1 000 €, capital 30 000 € et emprunt 15 000 €.<br><br>Au mois d’avril, il réalise notamment des achats et ventes à crédit ou au comptant, des retraits d’espèces, des règlements par chèque et des encaissements clients.`,
 table:{headers:['Date','Opération'],rows:[['5/4','Achat de marchandises à crédit au fournisseur Fogel : 1 800 €'],['6/4','Vente au comptant par chèque : 750 €'],['7/4','Retrait banque pour alimenter la caisse : 400 €'],['8/4','Vente à crédit au client Tiz : 1 000 €'],['9/4','Fournitures d’entretien payées en espèces : 35 €'],['11/4','Frais de transport payés par banque : 28 €'],['12/4','Chèque reçu du client Tiz : 300 €'],['14/4','Carburant payé par banque : 35 €'],['15/4','Abonnement à une revue : 136 €'],['16/4','Calculatrice payée par banque : 130 €'],['17/4','Achat de marchandises à crédit au fournisseur Cadet : 530 €'],['18/4','Timbres fiscaux électroniques : 32 €'],['19/4','Vente à crédit au client Dubois : 2 200 €'],['20/4','Règlement partiel au fournisseur Fogel : 600 €']]},
 questions:[{text:'Quel compte individuel utiliser pour le client Tiz ?',choices:['411001 Client Tiz','401001 Fournisseur Tiz','707 Ventes']},{text:'Quel compte débiter pour l’achat de marchandises du 5/4 ?',choices:['607 Achats de marchandises','707 Ventes de marchandises','512 Banques']},{text:'À quoi sert le libellé d’une écriture ?',choices:['Identifier le motif, la pièce justificative et le tiers','Calculer automatiquement le résultat','Remplacer les numéros de comptes']},{text:'Enregistrez toutes les opérations d’avril au journal.'}],
 correction:`Les comptes clients et fournisseurs sont subdivisés : 411001 Client Tiz, 411002 Client Dubois, 401001 Fournisseur Fogel, 401002 Fournisseur Cadet.<br><br>Exemples :<br>5/4 : débit 607 Achats de marchandises 1 800 € ; crédit 401001 Fournisseur Fogel 1 800 €.<br>6/4 : débit 512 Banques 750 € ; crédit 707 Ventes de marchandises 750 €.<br>7/4 : débit 530 Caisse 400 € ; crédit 512 Banques 400 €.<br>8/4 : débit 411001 Client Tiz 1 000 € ; crédit 707 Ventes 1 000 €.<br>Le total du journal s’élève à 52 976 € au débit et au crédit.<br><br>Le libellé permet d’identifier le motif, la pièce justificative et le tiers concerné.`
},
'T3-S2':{
 statement:`Monsieur Bouniort vous remet le journal du mois de juin, mois de création de l’entreprise.`,
 table:{headers:['Compte','Débit','Crédit'],rows:[['207 Fonds commercial','8 000',''],['2184 Mobilier','3 800',''],['370 Stock de marchandises','5 000',''],['512 Banques','3 200',''],['101 Capital','','20 000'],['275 Dépôts et cautionnements','500',''],['613 Locations','1 500',''],['512 Banques','','2 000'],['607 Achats de marchandises','2 400',''],['401 Fournisseurs','','2 400'],['411 Clients','900',''],['707 Ventes','','900'],['622 Honoraires','750',''],['512 Banques','','750'],['530 Caisse','150',''],['512 Banques','','150'],['625 Déplacements','285',''],['512 Banques','','285'],['411 Clients','1 260',''],['707 Ventes','','1 260'],['512 Banques','150',''],['411 Clients','','150'],['606 Achats non stockés','318',''],['512 Banques','','318'],['626 Télécommunications','35',''],['530 Caisse','','35']]},
 questions:[{text:'Quel est le solde du compte Banque ?',choices:['Créditeur de 153 €','Débiteur de 153 €','Nul']},{text:'Quel est le solde du compte Caisse ?',choices:['Débiteur de 115 €','Créditeur de 115 €','Débiteur de 150 €']},{text:'Quel est le chiffre d’affaires du mois ?',choices:['2 160 €','900 €','1 260 €']},{text:'Quel est le solde clients ?',choices:['Débiteur de 2 010 €','Créditeur de 2 010 €','Débiteur de 150 €']},{text:'Effectuez le report au grand livre et établissez la balance.'}],
 correction:`La balance totalise 28 248 € de mouvements au débit et au crédit. Les soldes débiteurs et créditeurs totalisent chacun 24 713 €.<br><br>Banque : solde créditeur de 153 €, correspondant à un découvert.<br>Caisse : solde débiteur de 115 €.<br>Ventes : solde créditeur de 2 160 €, soit le chiffre d’affaires.<br>Clients : solde débiteur de 2 010 €, soit les créances clients.`,
 correctionTable:{headers:['Compte','Mouvements débit','Mouvements crédit','Solde'],rows:[['512 Banques','3 350 €','3 503 €','153 € créditeur'],['530 Caisse','150 €','35 €','115 € débiteur'],['707 Ventes','0 €','2 160 €','2 160 € créditeur'],['411 Clients','2 160 €','150 €','2 010 € débiteur']]}
},
'T3-S3':{
 statement:`La société Golden, créée le 1er juin N−2, remet sa balance générale au 31 octobre N.`,
 table:{headers:['Compte','Mouvements débit','Mouvements crédit','Solde'],rows:[['164 Emprunts','26 200','75 000','48 800 créditeur'],['512 Banques','253 120','249 400','3 720 débiteur'],['514 Chèques postaux','63 280','62 350','930 débiteur'],['530 Caisse','9 500','6 750','2 750 débiteur'],['641 Rémunérations','225 170','','225 170 débiteur'],['645 Charges sociales','101 330','','101 330 débiteur'],['707 Ventes','','870 000','870 000 créditeur'],['708 Produits annexes','','1 300','1 300 créditeur']]},
 questions:[{text:'Montant initial de l’emprunt ?',choices:['75 000 €','48 800 €','26 200 €']},{text:'Remboursements déjà effectués ?',choices:['26 200 €','48 800 €','75 000 €']},{text:'Trésorerie disponible au 31 octobre ?',choices:['7 400 €','3 720 €','6 470 €']},{text:'Résultat provisoire ?',choices:['Perte de 14 450 €','Bénéfice de 14 450 €','Résultat nul']},{text:'Peut-on calculer les coûts salariaux depuis la création ?',choices:['Non, seulement ceux de l’exercice N','Oui, avec les comptes 641 et 645','Oui, grâce au capital'] }],
 correction:`Emprunt initial : 75 000 €. Remboursements : 26 200 €. Somme restant due : 48 800 €.<br>Trésorerie : 3 720 + 930 + 2 750 = 7 400 €.<br>Total des charges : 885 750 €. Total des produits : 871 300 €. Résultat provisoire : perte de 14 450 €.<br>Les coûts salariaux de l’exercice N sont de 326 500 €, mais la balance ne permet pas de connaître ceux supportés depuis la création.`
},
'T3-S4':{
 statement:`L’entreprise Delvart exerce une activité commerciale à la commande, sans stockage. Après une balance au 30 avril N, plusieurs opérations ont lieu en mai : acquisition informatique, achats de marchandises, règlements fournisseurs, ventes à crédit, ouverture d’un compte postal, charges externes et salaires.`,
 table:{headers:['Date','Opération'],rows:[['2/5','Ensemble informatique payé par banque : 2 800 €'],['3/5','Achats de marchandises à crédit : 8 500 €'],['4/5','Timbres-poste en espèces : 75 €'],['6/5','Règlement fournisseurs par banque : 4 500 €'],['9/5','Disque dur externe en espèces : 45 €'],['10/5','Ventes à crédit : 21 000 €'],['10/5','Virement BNP vers compte postal : 3 500 €'],['15/5','Achats de marchandises par chèque postal : 1 200 €'],['16/5','Facture Orange prélevée : 125 €'],['18/5','Personnel intérimaire payé par banque : 750 €'],['20/5','Salaire payé par virement : 2 450 €'],['23/5','Entretien véhicule par chèque postal : 125 €']]},
 questions:[{text:'Total de la balance au 31 mai ?',choices:['241 420 €','196 350 €','167 500 €']},{text:'Résultat au 31 mai ?',choices:['Bénéfice de 50 180 €','Perte de 50 180 €','Bénéfice de 68 320 €']},{text:'Total du bilan au 31 mai ?',choices:['99 180 €','118 500 €','80 180 €']},{text:'Disponibilités au bilan ?',choices:['14 880 €','12 625 €','2 175 €']},{text:'Enregistrez au journal, reportez au grand livre, établissez la balance, le compte de résultat et le bilan.'}],
 correction:`La balance au 31 mai totalise 241 420 € au débit et au crédit. Les soldes débiteurs et créditeurs totalisent chacun 167 500 €.<br>Charges : 68 320 €. Produits : 118 500 €. Résultat : bénéfice de 50 180 €.<br>Disponibilités : Banque 12 625 € + Chèques postaux 2 175 € + Caisse 80 € = 14 880 €.<br>Total du bilan : 99 180 €.` ,
 correctionTable:{headers:['Compte de résultat','Charges','Produits'],rows:[['Achats de marchandises','43 700 €',''],['Autres charges externes','2 670 €',''],['Salaires','21 950 €',''],['Ventes de marchandises','','118 500 €'],['Résultat','50 180 €','Bénéfice']]}
},
'T3-S5':{
 statement:`La société LMHT, entreprise de prêt-à-porter féminin, achète les vêtements à crédit et les vend au comptant en espèces, par chèques ou par cartes bancaires. Elle possède un compte BNP Paribas et un compte à La Banque Postale. La gérante comptabilise les opérations à l’aide d’un progiciel.`,
 questions:[{text:'Quels journaux divisionnaires créer ?',choices:['Achats, ventes, banque BNP, Banque Postale, caisse, opérations diverses','Un seul journal général','Achats et ventes uniquement']},{text:'Faut-il ouvrir des comptes clients individuels ?',choices:['Non, car les ventes sont au comptant','Oui, obligatoirement','Seulement pour les paiements en carte']},{text:'Faut-il ouvrir des comptes fournisseurs individuels ?',choices:['Oui, pour suivre les achats à crédit','Non','Seulement un compte collectif']},{text:'Dans quel journal enregistrer la paie ?',choices:['Opérations diverses','Journal des ventes','Journal de caisse']},{text:'Quel compte utiliser lors d’un transfert entre deux trésoreries ?',choices:['58 Virements internes','512 Banques uniquement','401 Fournisseurs']},{text:'La société doit-elle remettre le FEC en cas de contrôle ?',choices:['Oui, si la comptabilité est informatisée','Non','Seulement si elle emploie plus de 10 salariés']}],
 correction:`Journaux à créer : achats à crédit, ventes au comptant, banque BNP Paribas, Banque Postale, caisse et opérations diverses.<br>Pas de comptes clients individuels, car les ventes sont encaissées au comptant. Des comptes fournisseurs individuels sont nécessaires pour suivre les achats à crédit.<br>La paie est enregistrée dans le journal des opérations diverses ; les règlements dans les journaux de trésorerie.<br>Les transferts entre comptes de trésorerie utilisent le compte 58 Virements internes dans les deux journaux concernés.<br>La société doit remettre une copie dématérialisée du FEC lors d’un contrôle si sa comptabilité est informatisée.`
}
});